### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by tartsharpcobra** [DillyzThe1/PhoenixRole#2]
airship is in among us and you haven't updated. OMG

**Comment by DillyzThe1** [comment]
This mod is being reworked from the ground up entirely in latest versions of the game.
I will reply with a link to the mod manager's download when it releases before closing.

Also, hey aren't you the same person from the LAST issue?!

**Comment by DillyzThe1** [comment]
https://github.com/DillyzThe1/DRAPI-Mod-Manager#installation
